### ISSUE TITLE
runing the project

### ISSUE THREAD

**Issue by yxshwant** [JahidulPabelIslam/Restaurant-Recommender#5]
can you give the instructions to run the project?

**Comment by jahidulpabelislam** [comment]
Hey @yxshwant.

I'll try to take a look and provide something this week.

I must say I built this like 8 years and haven't worked on it since so things will be out of date.

**Comment by jahidulpabelislam** [comment]
Hi @yxshwant,

I'm afraid, it isn't in a working state.

We used Yelp API v2 and it looks that isn't accessible no more. At least I can't get new auth for the API to get it working.
